GET http://localhost:5000/products

###
GET http://localhost:5000/products/2

###
POST http://localhost:5000/products
Content-Type: application/json

{
    "name" : "Bola",
    "price" : 5900
}

###
PATCH http://localhost:5000/products/3
Content-Type: application/json

{
    "name" : "Product 3 Berubah",
    "price" : 19000
}

###
DELETE http://localhost:5000/products/2